language: go
# see https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
# for the detail
# sudo: requried
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - go get github.com/golang/lint/golint

before_script:
  - golint .
  - go fmt .
  - go vet .
  # was failing with: `gocyclo: vendor/golang.org/x/net/context/go19.go:15:14: expected type, found '=' (and 1 more errors)`
  # - gocyclo -over 15 .

script:
  - go build dummy.go

after_success:
  # stub.